 CREATE TABLE "ECEGOV"."Z_AUTHOR" 
   (	"AUTHOR_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20 BYTE), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "Z_AUTHOR_PK" PRIMARY KEY ("AUTHOR_ID")
	 );
	 
   COMMENT ON COLUMN "ECEGOV"."Z_AUTHOR"."AUTHOR_ID" IS '작가ID';
   COMMENT ON COLUMN "ECEGOV"."Z_AUTHOR"."NAME" IS '이름';
   COMMENT ON COLUMN "ECEGOV"."Z_AUTHOR"."FRST_REGIST_PNTTM" IS '최초등록시점';
   COMMENT ON COLUMN "ECEGOV"."Z_AUTHOR"."FRST_REGISTER_ID" IS '최초등록자ID';
   COMMENT ON COLUMN "ECEGOV"."Z_AUTHOR"."LAST_UPDT_PNTTM" IS '최종수정시점';
   COMMENT ON COLUMN "ECEGOV"."Z_AUTHOR"."LAST_UPDUSR_ID" IS '최종수정자ID';
   
    CREATE TABLE "ECEGOV"."Z_BOOK" 
   (	"BOOK_ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200 BYTE), 
	"AUTHOR_ID" NUMBER, 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20 BYTE), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20 BYTE), 
	"TOTAL_PAGE" NUMBER, 
	 CONSTRAINT "Z_BOOK_PK" PRIMARY KEY ("BOOK_ID")
	 );
	 
	 COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."BOOK_ID" IS '책ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."TITLE" IS '제목';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."AUTHOR_ID" IS '작가ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."FRST_REGIST_PNTTM" IS '최초등록시점';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."FRST_REGISTER_ID" IS '최초등록자ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."LAST_UPDT_PNTTM" IS '최종수정시점';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."LAST_UPDUSR_ID" IS '최종수정자ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."TOTAL_PAGE" IS '총페이지수';
   