  CREATE TABLE "Z_AUTHOR" 
   (	"AUTHOR_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20 BYTE), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20 BYTE), 
	"BIRTH_DAY" VARCHAR2(8 BYTE), 
	"HISTORY" CLOB, 
	"DEBUT_YEAR" NUMBER(4,0)
   ) ;

   COMMENT ON COLUMN "Z_AUTHOR"."AUTHOR_ID" IS '작가ID';
   COMMENT ON COLUMN "Z_AUTHOR"."NAME" IS '이름';
   COMMENT ON COLUMN "Z_AUTHOR"."FRST_REGIST_PNTTM" IS '최초등록시점';
   COMMENT ON COLUMN "Z_AUTHOR"."FRST_REGISTER_ID" IS '최초등록자ID';
   COMMENT ON COLUMN "Z_AUTHOR"."LAST_UPDT_PNTTM" IS '최종수정시점';
   COMMENT ON COLUMN "Z_AUTHOR"."LAST_UPDUSR_ID" IS '최종수정자ID';
   COMMENT ON COLUMN "Z_AUTHOR"."BIRTH_DAY" IS '생년월일';
   COMMENT ON COLUMN "Z_AUTHOR"."HISTORY" IS '작가이력';
   COMMENT ON COLUMN "Z_AUTHOR"."DEBUT_YEAR" IS '데뷔년도';

   
    CREATE TABLE "ECEGOV"."Z_BOOK" 
   (	"BOOK_ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200 BYTE), 
	"AUTHOR_ID" NUMBER, 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20 BYTE), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20 BYTE), 
	"TOTAL_PAGE" NUMBER, 
	 CONSTRAINT "Z_BOOK_PK" PRIMARY KEY ("BOOK_ID")
	 );
	 
	 COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."BOOK_ID" IS '책ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."TITLE" IS '제목';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."AUTHOR_ID" IS '작가ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."FRST_REGIST_PNTTM" IS '최초등록시점';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."FRST_REGISTER_ID" IS '최초등록자ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."LAST_UPDT_PNTTM" IS '최종수정시점';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."LAST_UPDUSR_ID" IS '최종수정자ID';
   COMMENT ON COLUMN "ECEGOV"."Z_BOOK"."TOTAL_PAGE" IS '총페이지수';
   